all:
  # global variables
  vars:
    netapp_hostname: uatnetapp.example.com
    netapp_username: admin
    netapp_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          123456789123456789123456789123456789123456789123456789123456789123456789.......
    vmware_datacenter: DC1
    vmware_cluster: Cluster1
    # san tasks first run against a single esxi host, so we need to specify it.
    # don't forget to change the esxi hostname in the vmware_host_datastore task
    # loop, found in both the nas_all_in_one.yml and nas_teardown.yml playbooks.
    vmware_esxi_host: dc1c1esxihost01.example.com
    # network map of a production network and their UAT equivilent. VM's that were originally
    # on the source network will be modified to use the specified destination network
    vmware_network_map:
       - { src: 'my-prod-network1', dest: '{{ uat_instance }}-my-prod-network1' }
       - { src: 'my-prod-network2', dest: '{{ uat_instance }}-my-prod-network2' }
    # production vcenter server. used by the network map module to query the networks
    # on your production virtual machine. username and password in this example is
    # provided by ENV variables, and is the same username/pass to login to your
    # testbed environment. if they are diffirent, modify playbooks/common/vmguest_tasks.yml
    # to use a diffirent 'provider' variable with the correct credentials.
    vmware_prod_host: prodvcenter.example.com
    datastore_name: '{{ uat_instance }} {{ inventory_hostname |replace("_", " ") }}'

  children:
    # grouping for SAN based volumes/datastores
    san:
      # non-static group specific vars
      vars:
        netapp_igroup: uat_igroup
        netapp_vserver: uatnetapp01_san
      children:
          app1:
            vars:
              vmware_folder: 'Application1'
            hosts:
              # hosts are the names of your NetApp volumes
              example_datastore_1:
              example_datastore_2:

          app2:
            vars:
              vmware_folder: 'Application2'
            hosts:
              example_datastore_3:
              example_datastore_4:

    # grouping for NAS based volumes/datastores
    nas:
      vars:
        netapp_vserver: uatnetapp01_nas
        netapp_junction_path: '/{{ uat_instance + "_" + inventory_hostname }}'
        netapp_lif: 172.16.0.1
      children:
        app3:
            vars:
              vmware_folder: 'Application3'
            hosts:
              example_datastore_5:

